### PR TITLE
Add support for more time of day mappings

### PR DESCRIPTION
**Pull request by ozontm**
- Changed Regex to support the newer TM mood values
- Added GetMappedTimeOfDay() to MP#View
- Tested within reasonable scope => [Regex101](https://regex101.com/r/XzZIHr/1)

### CODE REVIEW

**Comment by stefan-baumann** [comment]
Thank you very much for the contribution! May I ask what the background is with the additional mappings? The current mappings should already cover all of the different moods I am aware of in the wild.

**Comment by ozontm** [comment]
> Thank you very much for the contribution! May I ask what the background is with the additional mappings? The current mappings should already cover all of the different moods I am aware of in the wild.

There are new formats in which the moods are provided, sometimes with the actual underlying TimeOfDay in the beginning of the string.

Also, in the new Trackmania, the mood might not start with the size (e.g. `30x30`), but will start with a modifier (e.g. `NoStadium `in `NoStadium48x48Day`). I updated the Regex to catch those.

**Comment by stefan-baumann** [comment]
Okay, thank you very much for the info - I was not aware of that.

**Review by stefan-baumann — COMMENTED** [review]
Looks all good

**Pull request merged**
